### PR TITLE
'white-list' few more of CDC ACM compatible devices

### PR DESCRIPTION
**Pull request by lyusupov**

### CODE REVIEW

**Comment by kai-morich** [comment]
I am a bit reluctant to add IDs for CDC devices as there are many more CDC devices out there.
Please start with a custom prober as depicted here https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices

**Comment by lyusupov** [comment]
Ok. I can cancel the PR promptly.

But what was the reason to explicitly add Raspberry Pi Pico USB CDC device recently?

https://github.com/mik3y/usb-serial-for-android/pull/411

**Comment by kai-morich** [comment]
whitelist requests are typically merged for popular devices like ST, raspi.

**Comment by lyusupov** [comment]
Ok. Which one of the devices in the PR is, you think, not a popular one ? I can exclude it from the list.

**Comment by kai-morich** [comment]
Pi Pico SDK added with 1d4e0128c01c432299b0091c5e00648769101059

**Pull request closed without merging**
