### PR TITLE
Added CH34x driver

### PR DESCRIPTION
**Pull request by xseignard**
It is the same as #92 up to date with master.

I tested it in https://github.com/xseignard/cordovarduino/ and it works well.

Could you pleeeeease accept this PR?

Best regards

### CODE REVIEW

**Comment by xseignard** [comment]
Any updates to merge this?

**Comment by RePeet13** [comment]
Also hoping this can get merged, in order to (hopefully) enable support for kegboards based on CH340G converters in kegtab https://github.com/Kegbot/kegbot-android (a sister project to this it seems) @mik3y any comments here?

**Comment by xseignard** [comment]
Hello @RePeet13 because of the constant lack of feedback of the original maintainer, I made my own fork here: https://github.com/xseignard/usb-serial-for-android

It's kinda lame, because I guess we are a lot doing the same. If only @mik3y would give commit access to some others, we could continue to make this good lib growing instead of rotting.

**Comment by mik3y** [comment]
@xseignard sorry about that! I've been meaning to sit down and give the project some more love, but life's been busy. I would _love_ your help maintaining! Please bump any bugs or PRs and I'll move quicker.

**Comment by mik3y** [comment]
PS: Opened #131 to track new release.

**Pull request merged**
