### PR TITLE
Add support for Cr50 (Chromebook CCD)

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Comment by kai-morich** [comment]
please provide some references, e.g. where and how this can be used

**Comment by phcoder** [comment]
> please provide some references, e.g. where and how this can be used

This is explained at https://chromium.googlesource.com/chromiumos/third_party/hdctools/+/HEAD/docs/ccd.md#raw-access

This is mostly raw access and gives access to cr50 console, serial console and EC console. I use it to debug coreboot on my Chromebook.

**Comment by kai-morich** [comment]
please do not implement unsupported control line methods and but add `UnsupportedOperationException` stubs similar to GsmModemSerialDriver.
please add above link into the sourcefile.
When googeling for `Cr50`, users will not find related info. What about naming this driver `ChromiumOsCcd` ?

**Comment by phcoder** [comment]
Done with stubs and renamed to ChromeCcd

**Review by kai-morich — APPROVED** [review]

**Comment by kai-morich** [comment]
the [build](https://github.com/mik3y/usb-serial-for-android/actions/runs/6376688225/job/17304076912#step:4:74) failed, please add missing method

**Pull request merged**
