### PR TITLE
add missing ARDUINO usb products IDs

### PR DESCRIPTION
**Pull request by fatpat**

### CODE REVIEW

**Review by kai-morich — COMMENTED** [review]
I am a bit reluctant to add IDs for CDC devices as there are many more CDC devices out there.
* [here](https://github.com/arduino/ArduinoCore-avr/blob/master/boards.txt) + [here](https://github.com/arduino/ArduinoCore-samd/blob/master/boards.txt) even more PIDs are listed
* [here](http://www.linux-usb.org/usb.ids) none of the new are listed.

On the other side all PIDs for VID 0x2341 are already mapped in [device_filter.xml](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialExamples/src/main/res/xml/device_filter.xml) used for auto start, so looks ok.

What about using a custom prober instead?
Do you think you added the relevant IDs?

**Comment by fatpat** [comment]
I don't know, in fact, I'm trying to use SimpleUsbTerminal (which depends on usb-serial-for-android) and connecting to arduino MKR FOX 1200 does not work. So I looked in the sources and figured out this devices was not listed in. Then I decided to PR for all SAMD arduino devices known to date.

I have not even try it yet (the project won't build on my computer ... this is not related to the PR but to my computer)

**Comment by fatpat** [comment]
I managed to build the application but my phone does not switch to USB host mode. I think I'm not using a proper cable. I ordered one and will give it another try tomorrow.

Will be back 😊

**Comment by fatpat** [comment]
nerverming, it works in fact, I can force the protocol so no need to PR

**Pull request closed without merging**
