### PR TITLE
Implemented CH340 driver

### PR DESCRIPTION
**Pull request by andreasb242**
CH340G is e.g. build on cheap chinese Arduino Clones

Not complete tested, and not all features are implemented.

### CODE REVIEW

**Comment by 4ntoine** [comment]
are there any c/c++ sources?

**Comment by andreasb242** [comment]
No, only this single Java class.

It supports serial in and out (tested with a chinese arduino clone). Not all handshake bits are implemented, because I hadn’t a specification and they were not connected.

I thought I pull it anyway, in the hope it helps somebody else.

**Comment by 4ntoine** [comment]
No problem. I've meant what c++ sources or CH340 documentation you used to create Java code?

**Comment by 4ntoine** [comment]
What about 57600 baud rate? Is it supported by CH34x chips? https://github.com/andreasb242/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/CH34xSerialDriver.java#L274

**Comment by andreasb242** [comment]
> No problem. I've meant what c++ sources or CH340 documentation you used to create Java code?
To long ago, I don't know any more.
I didn't find any documentation about the protocol, but some Linux driver example. I cannot tell you the exact source, but I think it was something similar to http://www.cs.fsu.edu/~baker/devices/lxr/http/source/linux/drivers/usb/serial/ch341.c?v=2.6.25.8

I only needed the initialisation, data transfer was copied from the FTDI implementation, I think.

>What about 57600 baud rate? Is it supported by CH34x chips?
I tested it now with a module on my Ubuntu PC, it was working, but I didn't check the baud rate, I only shorted RX and TX.
I'll check it with the scope, if it's really 57600, then I should be able to look at the kernel source.

The chips are very cheap, you can get an USB - UART Adapter for less than 1 USD from the Chinese.
I have now some of them here, I may also can control the additional Pins, I have to check it, but not today...

**Comment by dack** [comment]
I can't seem to build this. It fails with the error shown below. Looking at the pull request diff, I'm not seeing anywhere these are defined. Maybe something missing in the commit?

```
usb-serial-for-android\usbSerialForAndroid\src\main\java\com\hoho\android\usbserial\driver\CH34xSerialDriver.java:357: error: cannot find symbol
                supportedDevices.put(UsbId.VENDOR_QINHENG, new int[]{
                                          ^
  symbol:   variable VENDOR_QINHENG
  location: class UsbId
usb-serial-for-android\usbSerialForAndroid\src\main\java\com\hoho\android\usbserial\driver\CH34xSerialDriver.java:358: error: cannot find symbol
                                UsbId.QINHENG_HL340
                                     ^
  symbol:   variable QINHENG_HL340
  location: class UsbId
2 errors
:usbSerialForAndroid:compileReleaseJava FAILED
```

**Comment by boogerlad** [comment]
this will fix it https://github.com/andreasb242/usb-serial-for-android/pull/1

**Comment by mik3y** [comment]
Merged in #121

**Pull request closed without merging**
