### PR TITLE
ST CDC

### PR DESCRIPTION
**Pull request by rusefi**
See https://www.the-sz.com/products/usbid/index.php?v=0483&p=&n=

### CODE REVIEW

**Comment by rusefi** [comment]
I guess this could go the #196 way? :(

**Comment by kai-morich** [comment]
I prefer, you use a custom prober as depicted here https://github.com/mik3y/usb-serial-for-android#probing-for-unrecognized-devices. with that solution you can use the libary as is for any CDC device

**Comment by rusefi** [comment]
A better / alternative example would be expanding default table with custom probing, not create a separate prober which does not benefit from default table.

**Comment by kai-morich** [comment]
you can do that already in your CustomProber by initializing the probe table with `UsbSerialProber.getDefaultProbeTable()`.

I will have a look at such simplification in the example app

**Pull request merged**
